[package]
name = "SwitchboardFeedParser"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "testnet" }
switchboard = { git = "https://github.com/switchboard-xyz/sbv2-sui.git", subdir = "move/switchboard/", rev = "main"  }

[addresses]
switchboard_feed_parser = "0x0"
std = "0x1"
sui =  "0x2"
switchboard = "0x3ad959d0446d971062f6b93bb88b9f3ffcb7abb5fa6515eb4b9c09b7280d0c7c"
